### ISSUE TITLE
Truncated text (layout issue?)

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/FtpPositive#10]
Text for "Remote Directory" on main application window, and "Remote Path" on New Bookmark are both truncated. Screenshots attached.

![ftppositive](https://user-images.githubusercontent.com/13264393/34396529-7a646f0e-eb29-11e7-8796-38dc9f993359.png)
![new_bookmark](https://user-images.githubusercontent.com/13264393/34396530-7f297a20-eb29-11e7-90e5-bd8e70ecd77a.png)

**Comment by janus2** [comment]
Is this is fixed with Damillora PR #16? 
If am I wrong please reopen the issue.

**Comment by Vidrep** [comment]
Looks OK now.
