### ISSUE TITLE
The icon is missing from the package for Haiku

### ISSUE THREAD

**Issue by richienyhus** [HaikuArchives/FtpPositive#2]
As Urias McCullough stated in a GCI2013 task:

"It seems there's no icon for FtpPositive, but I suspect this might be an issue with the software itself, unrelated to the recipe. The Jamfile appears to add a rsrc file."

**Comment by Vidrep** [comment]
There is a nice icon for FtpPositive shown in the HaikuDepot list, but when installed all we get is the generic application icon in the menu.
![screenshot1](https://user-images.githubusercontent.com/13264393/34505643-8eabfcc0-efe3-11e7-9d96-a866de4b249a.png)

**Comment by diversys** [comment]
Added icon in 735ce67641b88668f371adcf30e5f7bd85c47b97.

**Comment by janus2** [comment]
I think this is solved. Can we close this?

**Comment by diversys** [comment]
Yep, just need to update the recipe. I can do that if you're done with fixes for now.

**Comment by janus2** [comment]
Yes, I think all the major problems are solved.

**Comment by janus2** [comment]
I don't know if we should try to receive translations for the app before the release. What do you think?

**Comment by humdingerb** [comment]
I wanted to do some small changes to the GUI strings. And also some changes in the code.
If we could postpone to a week after GCI finished, that might give me a chance... :)
OTOH, we can always push out a quick point release anytime. PM&updates rule!

**Comment by scottmc** [comment]
Fixed in 735ce67641b88668f371adcf30e5f7bd85c47b97.
