### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/FtpPositive#29]
![image](https://user-images.githubusercontent.com/1316513/34672214-b440c204-f48e-11e7-83ff-49d34ed00ffd.png)

**Comment by diversys** [comment]
* Count view is not properly redrawn during resize
* Idle/Use this connection could be moved lower
* Column artefacts
* Log view text is cut off
* Close button could be taken from Web+ maybe?

**Comment by janus2** [comment]
The third point is related to https://dev.haiku-os.org/ticket/3037.

**Comment by janus2** [comment]
Something like this? There is a split in the middle of the window
@humdingerb your opinion is always appreciated...

![reworkedlayout](https://user-images.githubusercontent.com/10423645/34680004-061fdb60-f498-11e7-8424-1f3566bd6dac.png)

**Comment by diversys** [comment]
Looks good. Maybe adding a few pixels before the text to disconnect it from the border?
Also Maybe making the splitter a bit narrower?

**Comment by humdingerb** [comment]
Yay, split view! :)
Looks good. Maybe not to big a padding above/below the split dot line. If one collapses the split view, it'll oterwise take more space than needed. The split view setting (height and if collapsed) should of course be saved... :)
The padding above/below the tool bar should be equal.
A bit of strut between the tool buttons to the left and the "Remote dir" text box would be nice as well. Maybe rename to "Remote:"; should be clear enough.

**Comment by janus2** [comment]
> Maybe adding a few pixels before the text to disconnect it from the border?

Are you talking about the log view? I din't change anything there because it's pointless the BTextView do what they want... ;-)

**Comment by janus2** [comment]
@humdingerb too much requests I have a big fever I cannot process such complex task...

**Comment by janus2** [comment]
Baby steps...

**Comment by janus2** [comment]
This is the best I can do with half brain working.
Is it ok?

![lastchanges](https://user-images.githubusercontent.com/10423645/34681675-e5dd374e-f49c-11e7-897c-fce9b856f13e.png)

**Comment by humdingerb** [comment]
Half a brain seems to work fine for you. :)
Very nice. And you don't have to do everything at once. And not on your own, either. :)
Well done all around. 'Twas a pleasure to see how quickly FtpPositive evolved!   :1st_place_medal:

**Comment by janus2** [comment]
In the commit there is a little surprise for @diversys ...

**Comment by diversys** [comment]
You mean close button? :) Looks good but it doesn't draw a border on mouse over. Also now there are even more drawing artefacts ...

![image](https://user-images.githubusercontent.com/1316513/34685436-5c5cb810-f4b9-11e7-8808-44d6cc38d635.png)

**Comment by diversys** [comment]
Oh and padding below the tool bar appears on splitter resize from the top.

**Comment by janus2** [comment]
The button has nothing to do with the redrawing problem you can read the motivation in the haiku ticket I wrote at the top of the issue. The button you choose became darker when the mouse is over and lighter when the mouse is not over...  there is a button around when is pressed. But in this application most of the time is disabled.

**Comment by janus2** [comment]
This are all bugs present in Haiku. Writing app that uses some features is useful to discover this problem... I can revert the commit if you think

**Comment by diversys** [comment]
Yeah, I know that the button is not to blame. Interestingly, Web+ has two close buttons: in find panel and in tabview... Please don't revert, it's not that one will resize this little app all the time ;)

**Comment by diversys** [comment]
I think Web+ should use close button from tabview for consistency and it should get a border on mouse over. Same thing in notification_server window.

**Comment by janus2** [comment]
> I think Web+ should use close button from tabview for consistency and it should get a border on mouse over. Same thing in notification_server window.
With Web+ do you mean FtpPositive?

I will commit a nasty hack that will minimize the redraw issue...

**Comment by diversys** [comment]
I meant Web+. Need to create an issue about this in Haiku's Trac.

**Comment by janus2** [comment]
With the last commit the glitches should be only in the menubar and less frequent. Let me know

**Comment by diversys** [comment]
Confirmed, it now flickers instead which is fine I guess. Thanks! :)
