### ISSUE TITLE
Replace close button with Web+'s tabview

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/FtpPositive#32]
...and add a border around it on mouse over.

**Comment by janus2** [comment]
Can you explain better to me they are the same

![find](https://user-images.githubusercontent.com/10423645/34687945-b3dc6530-f4b0-11e7-86d4-7178ac512031.png)
![tab](https://user-images.githubusercontent.com/10423645/34687946-b55f4918-f4b0-11e7-860f-81946b23e581.png)

**Comment by diversys** [comment]
The one in tabview has pressed state.

**Comment by janus2** [comment]
The one in FTPPositive has pressed state too but works only when the app is loading the list and is very fast.
![close button pressed](https://user-images.githubusercontent.com/10423645/34688304-f39ed4d6-f4b1-11e7-9aee-334accb0fbec.png)

**Comment by janus2** [comment]
You can put the mouse over the X press ALT-R and press the mouse button... or you need a very slow FTP server with a lot of files

**Comment by diversys** [comment]
Ah, I didn't realise it works only when the app is loading the list. Then all is needed is to add a border on mouse over :)

**Comment by janus2** [comment]
I tried it doesn't look pretty... There is the difference in tint when the mouse is over that look nice

**Comment by diversys** [comment]
If it doesn't look pretty shall we close it then?

**Comment by janus2** [comment]
I don't know we can ask @humdingerb the sage ;-) any ideas?

**Comment by humdingerb** [comment]
Well, ideal would be to change the "Refresh" button to a "X" button while the list is built.
Frankly, until a second ago I didn't know exactly what the current "x" button did. Thought it disconnected... :)
I only tried my local NAS, which is quick and doesn't have huge folders...

**Comment by janus2** [comment]
We live in a perfect world...
