### ISSUE TITLE
Choosing a license

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/FtpPositive#41]
This is going out to everyone that touched the FtpPositive code:

@janus2, @diversys, @sfanxiang, @Damillora, @owenca, @waddlesplash, @ModeenF, @KapiX
(I have email addresses for some of you, that I'll have to try should someone not comment here.)

The original author "Momoziro" never chose a license and now that we'd like to publish the application as a package, we need one. As we were unable to contact Momoziro, we should choose one.

I suggest the most permissible "[Unlicense](https://choosealicense.com/licenses/unlicense/)". In the LICENSE file, I'd prepend as explanation:

> The original author "Momoziro" hasn't chosen a license for FtpPositive and despite best efforts, all tries to contact him failed. In the Japanese ReadmeJP.txt he states (Google translated), "It is free software. It is under development. No matter what happens, at your own risk."
>The source has been available since at least 2007 at http://www.mars.dti.ne.jp/~momoziro/archive/FtpPositive/.
>All other contributers have agreed to using "The Unlicense" (below) until the original author makes his wishes known.

Discuss or +1 to confirm your agreement (if you don't care about the exact license and are OK with any open license, say so too, then you won't have to get involved if a possible discussion ends with us choosing another license in the end...).

Should Momoziro ever make an appearance to let us know his wishes, we can re-visit the issue.

**Comment by KapiX** [comment]
Unlicense has some problems:
https://en.wikipedia.org/wiki/Unlicense#Reception

Either CC0 or MIT is fine for me, though I prefer MIT.

2018-02-16 14:29 GMT+01:00 humdinger <notifications@github.com>:

**Comment by humdingerb** [comment]
I'm OK with any open license. "MIT" is OK, too, maybe better as it's more standard/known than the "Unlicense".

**Comment by diversys** [comment]
I don't really care about the exact license.

**Comment by janus2** [comment]
I'm fine with the license you will choose.

**Comment by sfanxiang** [comment]
I'm OK with any open license too, though I would prefer MIT.

**Comment by owenca** [comment]
I don't care about the exact license and am OK with any open license.

**Comment by humdingerb** [comment]
Still missing are the votes of @Damillora , @waddlesplash and @ModeenF . I got the mail address for Frederik that I try now too.

**Comment by humdingerb** [comment]
@ModeenF answered via mail:

"+1 for MIT but anything except gpl is fine..."

**Comment by Damillora** [comment]
+1 for MIT

**Comment by humdingerb** [comment]
Thanks everyone. Until Momoziro decides otherwise, we now go with MIT.
