### ISSUE TITLE
FtpPositive broken on hrev56588

### ISSUE THREAD

**Issue by bbjimmy** [HaikuArchives/FtpPositive#56]
Does not run, Missing symbol:_ZTIBRow.

Does not compile from source.

compile errors:

undefined reference to `BPrivate::BToolBar::AddAction(BMessage*, BHandler*, BBitmap const*, char const*, char const*, bool)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/11.2.0/../../../../x86_64-unknown-haiku/bin/ld: FTPWindow.cpp:(.text+0x2b63): undefined reference to `BPrivate::BToolBar::AddView(BView*)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/11.2.0/../../../../x86_64-unknown-haiku/bin/ld: FTPWindow.cpp:(.text+0x388b): undefined reference to `BPrivate::BToolBar::FindButton(unsigned int) const'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/11.2.0/../../../../x86_64-unknown-haiku/bin/ld: FTPWindow.cpp:(.text+0x38aa): undefined reference to `BPrivate::BToolBar::FindButton(unsigned int) const'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/11.2.0/../../../../x86_64-unknown-haiku/bin/ld: FTPWindow.cpp:(.text+0x38c9): undefined reference to `BPrivate::BToolBar::FindButton(unsigned int) const'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/11.2.0/../../../../x86_64-unknown-haiku/bin/ld: FTPWindow.cpp:(.text+0x38e8): undefined reference to `BPrivate::BToolBar::FindButton(unsigned int) const'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/11.2.0/../../../../x86_64-unknown-haiku/bin/ld: FTPWindow.cpp:(.text+0x3907): undefined reference to `BPrivate::BToolBar::FindButton(unsigned int) const'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/11.2.0/../../../../x86_64-unknown-haiku/bin/ld: objects.x86_64-cc11-release/ProgressWindow.o: in function `TProgressView::SetTo(char const*, long, bool)':
ProgressWindow.cpp:(.text+0x145): undefined reference to `BPrivate::string_for_size(double, char*, unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/11.2.0/../../../../x86_64-unknown-haiku/bin/ld: ProgressWindow.cpp:(.text+0x18d): undefined reference to `BPrivate::string_for_size(double, char*, unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/11.2.0/../../../../x86_64-unknown-

haiku/bin/ld: objects.x86_64-cc11-release/ProgressWindow.o: in function `TProgressView::Update()':
ProgressWindow.cpp:(.text+0x2d1): undefined reference to `BPrivate::string_for_size(double, char*, unsigned long)'
collect2: error: ld returned 1 exit status
/boot/system/develop/etc/makefile-engine:249: recipe for target 'objects.x86_64-cc11-release/FtpPositive' failed
make: *** [objects.x86_64-cc11-release/FtpPositive] Error 1
~/Desktop/FtpPositive-master/src>

**Comment by humdingerb** [comment]
Fixed with [48a5acd](https://github.com/HaikuArchives/FtpPositive/commit/48a5acdfe0981697018abf151a82802f4f3e500e). Thanks for reporting.
