### ISSUE TITLE
FtpPositive crash when trying to start the application

### ISSUE THREAD

**Issue by unspacyar** [HaikuArchives/FtpPositive#57]
FtpPositive crashes when trying to start the application.
app version: 1.2.2-7 (32 bit)
Haiku nightly hrev57691

Crash report:

<details>
Debug information for team /boot/system/apps/FtpPositive/FtpPositive (5018):
CPU(s): 4x AMD A-Series
Memory: 3.90 GiB total, 859.53 MiB used
Haiku revision: hrev57691 Apr  5 2024 06:02:21 (BePC)

Active Threads:
	thread 5023: w>FtpPositive: Upload 
	thread 5032: team 5018 debug task 
	thread 5018: FtpPositive (main)
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x7219cb50	0x18dafe8	BView::_InvalidateParentLayout() + 0xd8 
			Disassembly:
				BView::_InvalidateParentLayout():
				0x018daf10:               55  push %ebp
				0x018daf11:             89e5  mov %esp, %ebp
				0x018daf13:           83ec0c  sub $0xc, %esp
				0x018daf16:               57  push %edi
				0x018daf17:               56  push %esi
				0x018daf18:               53  push %ebx
				0x018daf19:       e800000000  call 0x18daf1e
				0x018daf1e:               5b  pop %ebx
				0x018daf1f:     81c31e021600  add $0x16021e, %ebx
				0x018daf25:           8b4508  mov 0x8(%ebp), %eax
				0x018daf28:         83784400  cmp $0x0, 0x44(%eax)
				0x018daf2c:     0f84e7000000  jz 0x18db019
				0x018daf32:     8b8090000000  mov 0x90(%eax), %eax
				0x018daf38:           8b4024  mov 0x24(%eax), %eax
				0x018daf3b:             85c0  test %eax, %eax
				0x018daf3d:             7411  jz 0x18daf50
				0x018daf3f:           83c4f4  add $0xfffffff4, %esp
				0x018daf42:               50  push %eax
				0x018daf43:       e8f864f8ff  call 0x1861440
				0x018daf48:           83c410  add $0x10, %esp
				0x018daf4b:             89c1  mov %eax, %ecx
				0x018daf4d:             eb03  jmp 0x18daf52
				0x018daf4f:               90  nop 
				0x018daf50:             31c9  xor %ecx, %ecx
				0x018daf52:             85c9  test %ecx, %ecx
				0x018daf54:             7426  jz 0x18daf7c
				0x018daf56:           8b4108  mov 0x8(%ecx), %eax
				0x018daf59:           83c4f8  add $0xfffffff8, %esp
				0x018daf5c:           83c4fe  add $0xfffffffe, %esp
				0x018daf5f:           666a00  push $0x0
				0x018daf62:   0fbf90b0000000  movsx 0xb0(%eax), %edx
				0x018daf69:             01ca  add %ecx, %edx
				0x018daf6b:               52  push %edx
				0x018daf6c:     8b80b4000000  mov 0xb4(%eax), %eax
				0x018daf72:             ffd0  call *%eax
				0x018daf74:       e9a0000000  jmp 0x18db019
				0x018daf79:           8d7600  lea (%esi), %esi
				0x018daf7c:           8b5508  mov 0x8(%ebp), %edx
				0x018daf7f:           83c4f4  add $0xfffffff4, %esp
				0x018daf82:     8b8290000000  mov 0x90(%edx), %eax
				0x018daf88:           83c02c  add $0x2c, %eax
				0x018daf8b:               50  push %eax
				0x018daf8c:       e8bb4d0200  call 0x18ffd4c
				0x018daf91:           83c410  add $0x10, %esp
				0x018daf94:             85c0  test %eax, %eax
				0x018daf96:             7e6c  jle 0x18db004
				0x018daf98:           8b5508  mov 0x8(%ebp), %edx
				0x018daf9b:           83c4f4  add $0xfffffff4, %esp
				0x018daf9e:     8b8290000000  mov 0x90(%edx), %eax
				0x018dafa4:           83c02c  add $0x2c, %eax
				0x018dafa7:               50  push %eax
				0x018dafa8:       e89f4d0200  call 0x18ffd4c
				0x018dafad:             89c7  mov %eax, %edi
				0x018dafaf:             31f6  xor %esi, %esi
				0x018dafb1:           83c410  add $0x10, %esp
				0x018dafb4:             39fe  cmp %edi, %esi
				0x018dafb6:             7d61  jge 0x18db019
				0x018dafb8:           8b5508  mov 0x8(%ebp), %edx
				0x018dafbb:           83c4f8  add $0xfffffff8, %esp
				0x018dafbe:           83c4f4  add $0xfffffff4, %esp
				0x018dafc1:           83c4f8  add $0xfffffff8, %esp
				0x018dafc4:     8b8290000000  mov 0x90(%edx), %eax
				0x018dafca:           83c02c  add $0x2c, %eax
				0x018dafcd:               56  push %esi
				0x018dafce:               50  push %eax
				0x018dafcf:       e80c490900  call 0x196f8e0
				0x018dafd4:           83c410  add $0x10, %esp
				0x018dafd7:               50  push %eax
				0x018dafd8:       e86364f8ff  call 0x1861440
				0x018dafdd:             89c1  mov %eax, %ecx
				0x018dafdf:           83c4fe  add $0xfffffffe, %esp
				0x018dafe2:           8b5108  mov 0x8(%ecx), %edx
				0x018dafe5:           666a00  push $0x0
				0x018dafe8:   0fbf82b0000000  movsx 0xb0(%edx), %eax <--

			Frame memory:
				[0x7219cb14]  .....n/.......9.   00 00 8d 01 88 6e 2f 18 ad af 8d 01 ac ee 39 18
				[0x7219cb24]  ....X..r....<...   02 00 00 00 58 cb 19 72 1e af 8d 01 3c b1 a3 01
				[0x7219cb34]  ......:."...<...   00 00 00 00 80 b9 3a 18 22 9c 8e 01 3c b1 a3 01
				[0x7219cb44]  ...rx..r1...       88 cb 19 72 78 cb 19 72 31 a9 8d 01
		0x7219cb80	0x18da92c	BView::InvalidateLayout(bool) + 0xcc 
		0x7219cbb0	0x18db014	BView::_InvalidateParentLayout() + 0x104 
		0x7219cbe0	0x18da92c	BView::InvalidateLayout(bool) + 0xcc 
		0x7219cc10	0x18bce1a	BTextView::SetFontAndColor(int32, int32, BFont*, uint32, rgb_color*) + 0xae 
		0x7219cc50	0x18bcd5d	BTextView::SetFontAndColor(BFont*, uint32, rgb_color*) + 0x35 
		0x7219cce0	0x18b7160	BTextControl::_UpdateTextViewColors(bool) + 0x108 
		0x7219cd30	0x18b5682	BTextControl::AttachedToWindow() + 0x32 
		0x7219cd60	0x18dc178	BView::_Attach() + 0xa4 
		0x7219cd90	0x18dc1f2	BView::_Attach() + 0x11e 
		0x7219cdd0	0x18d8648	BView::_AddChild(BView*) + 0xf0 
		0x7219ce10	0x18600c5	BLayout::AddItem(int32, BLayoutItem*) + 0x8d 
		0x7219ce40	0x1846416	BGroupLayout::AddItem(int32, BLayoutItem*) + 0x22 
		0x7219ce80	0x185ff24	BLayout::AddView(int32, BView*) + 0x108 
		0x7219ceb0	0x184631a	BGroupLayout::AddView(int32, BView*) + 0x22 
		0x7219cee0	0x185fe12	BLayout::AddView(BView*) + 0x32 
		0x7219cf10	0x18462ea	BGroupLayout::AddView(BView*) + 0x1e 
		0x7219d0c0	0x126b54a	__10TFTPWindowG5BRectPCc + 0x11ce 
		0x7219d2a0	0x1268cc7	__12TFtpPositive + 0x513 
		0x7219d3e0	0x12692a5	main + 0x21 
		0x7219d408	0x124a17a	_start + 0x56 
		0x7219d448	0x1a7d3d2	runtime_loader + 0x132 
		00000000	0x64aad250	commpage_thread_exit + 0 

		Registers:
			  eip:	0x018dafe8
			  esp:	0x7219cb14
			  ebp:	0x7219cb48
			  eax:	0x182f3d28
			  ebx:	0x01a3b13c
			  ecx:	0x182f3d28
			  edx:	0x00000000
			  esi:	0x00000000
			  edi:	0x00000001
			   cs:	0x001b
			   ds:	0x0023
			   es:	0x0023
			   fs:	0x0063
			   gs:	0x0023
			   ss:	0x0023
			  st0:	121
			  st1:	242
			  st2:	1
			  st3:	1
			  st4:	1
			  st5:	2
			  st6:	1
			  st7:	0
			  mm0:	{0, 0, 0, 0xf200}
			  mm1:	{0, 0, 0, 0xf200}
			  mm2:	{0, 0, 0, 0x8000}
			  mm3:	{0, 0, 0, 0x8000}
			  mm4:	{0, 0, 0, 0x8000}
			  mm5:	{0, 0, 0, 0x8000}
			  mm6:	{0, 0, 0, 0x8000}
			  mm7:	{0, 0, 0, 0}
			 xmm0:	{0xdf61, 0x8be4, 0x93ea, 0x11d2, 0xdaa, 0xe000, 0x398, 0x8c2b}
			 xmm1:	{0xb828, 0xd2b2, 0x826, 0x48a7, 0xdfb3, 0x3c98, 0x6000, 0xf024}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0x1fc, 0x5ca, 0xfc1, 0x11dc, 0x1190, 0x1700, 0x5331, 0xa8eb}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	11597	0x008cc000	0x00a3e000	0x00a3e000	0x00a72000	lib    	/boot/system/lib/libicuuc.so.57.2
	11603	0x00c7f000	0x00c88000	0x00c88000	0x00c8a000	add-on 	/boot/system/add-ons/locale/catalogs/plaintext
	11598	0x00cb0000	0x00cc3000	0x00cc3000	0x00cc6000	lib    	/boot/system/lib/libz.so.1.3
	11589	0x00d69000	0x00d94000	0x00d94000	0x00d9e000	lib    	/boot/system/lib/libnetwork.so
	11599	0x00e86000	0x00f4f000	0x00f4f000	0x00f50000	lib    	/boot/system/lib/libzstd.so.1.5.5
	11592	0x00fe7000	0x01019000	0x01019000	0x01026000	lib    	/boot/system/lib/libstdc++.r4.so
	11587	0x0122b000	0x01280000	0x01280000	0x0128f000	app    	/boot/system/apps/FtpPositive/FtpPositive
	11596	0x013df000	0x013e8000	0x013e8000	0x013e9000	lib    	/boot/system/lib/libicuio.so.57.2
	11593	0x014f7000	0x015d6000	0x015d6000	0x015f2000	lib    	/boot/system/lib/libroot.so
	11605	0x0160b000	0x0160c000	0x0160c000	0x0160d000	add-on 	/boot/system/apps/FtpPositive/add-ons/encoders/EUC-JP
	11588	0x016d5000	0x019bd000	0x019bd000	0x01a5a000	lib    	/boot/system/lib/libbe.so
	11586	0x01a6c000	0x01a88000	0x01a88000	0x01a8a000	lib    	/boot/system/runtime_loader
	11604	0x01b29000	0x01b2a000	0x01b2a000	0x01b2b000	add-on 	/boot/system/apps/FtpPositive/add-ons/encoders/Shift-JIS
	11601	0x01b30000	0x01c27000	0x01c27000	0x01c29000	lib    	/boot/system/lib/libtextencoding.so
	11591	0x01c5f000	0x01e2f000	0x01e2f000	0x01e93000	lib    	/boot/system/lib/libtracker.so
	11600	0x020fb000	0x02105000	0x02105000	0x02106000	lib    	/boot/system/lib/libbsd.so
	11595	0x02142000	0x023d2000	0x023d2000	0x0243c000	lib    	/boot/system/lib/libicui18n.so.57.2
	11590	0x026ab000	0x026c2000	0x026c2000	0x026c7000	lib    	/boot/system/lib/libtranslation.so
	11594	0x026f4000	0x03f74000	0x03f74000	0x03f75000	lib    	/boot/system/lib/libicudata.so.57.2
	11585	0x64aad000	0x64ab5000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	43139	0x0035e000	0x0036e000	        64	rw-        	none          	rld heap
	43140	0x006bf000	0x006c0000	         4	rw-cS      	none          	_rld_debug_
	43178	0x00747000	0x0074f000	        32	rw-        	none          	rld heap
	43179	0x008a7000	0x008b7000	        64	rw-        	none          	rld heap
	43180	0x008ba000	0x008ca000	        64	rw-        	none          	rld heap
	43167	0x008cc000	0x00a3e000	      1480	r-x        	none          	libicuuc.so.57.2_seg0ro
	43168	0x00a3e000	0x00a71000	       204	rw-        	none          	libicuuc.so.57.2_seg1rw
	43169	0x00a71000	0x00a72000	         4	rw-        	none          	libicuuc.so.57.2_seg2rw
	43184	0x00c7f000	0x00c88000	        36	r-x        	none          	plaintext_seg0ro
	43185	0x00c88000	0x00c8a000	         8	rw-        	none          	plaintext_seg1rw
	43170	0x00cb0000	0x00cc3000	        76	r-x        	none          	libz.so.1.3_seg0ro
	43171	0x00cc3000	0x00cc6000	        12	rw-        	none          	libz.so.1.3_seg1rw
	43146	0x00d69000	0x00d94000	       172	r-x        	none          	libnetwork.so_seg0ro
	43147	0x00d94000	0x00d96000	         8	rw-        	none          	libnetwork.so_seg1rw
	43148	0x00d96000	0x00d9e000	        32	rw-        	none          	libnetwork.so_seg2rw
	43172	0x00e86000	0x00f4f000	       804	r-x        	none          	libzstd.so.1.5.5_seg0ro
	43173	0x00f4f000	0x00f50000	         4	rw-        	none          	libzstd.so.1.5.5_seg1rw
	43154	0x00fe7000	0x01019000	       200	r-x        	none          	libstdc++.r4.so_seg0ro
	43155	0x01019000	0x01024000	        44	rw-        	none          	libstdc++.r4.so_seg1rw
	43156	0x01024000	0x01026000	         8	rw-        	none          	libstdc++.r4.so_seg2rw
	43141	0x0122b000	0x01280000	       340	r-x        	none          	FtpPositive_seg0ro
	43142	0x01280000	0x0128f000	        60	rw-        	none          	FtpPositive_seg1rw
	43165	0x013df000	0x013e8000	        36	r-x        	none          	libicuio.so.57.2_seg0ro
	43166	0x013e8000	0x013e9000	         4	rw-        	none          	libicuio.so.57.2_seg1rw
	43157	0x014f7000	0x015d6000	       892	r-x        	none          	libroot.so_seg0ro
	43158	0x015d6000	0x015ea000	        80	rw-        	none          	libroot.so_seg1rw
	43159	0x015ea000	0x015f2000	        32	rw-        	none          	libroot.so_seg2rw
	43195	0x0160b000	0x0160c000	         4	r-x        	none          	EUC-JP_seg0ro
	43196	0x0160c000	0x0160d000	         4	rw-        	none          	EUC-JP_seg1rw
	43143	0x016d5000	0x019bd000	      2976	r-x        	none          	libbe.so_seg0ro
	43144	0x019bd000	0x01a59000	       624	rw-        	none          	libbe.so_seg1rw
	43145	0x01a59000	0x01a5a000	         4	rw-        	none          	libbe.so_seg2rw
	43137	0x01a6c000	0x01a88000	       112	r-x        	none          	runtime_loader_seg0ro
	43138	0x01a88000	0x01a8a000	         8	rw-        	none          	runtime_loader_seg1rw
	43193	0x01b29000	0x01b2a000	         4	r-x        	none          	Shift-JIS_seg0ro
	43194	0x01b2a000	0x01b2b000	         4	rw-        	none          	Shift-JIS_seg1rw
	43176	0x01b30000	0x01c27000	       988	r-x        	none          	libtextencoding.so_seg0ro
	43177	0x01c27000	0x01c29000	         8	rw-        	none          	libtextencoding.so_seg1rw
	43151	0x01c5f000	0x01e2f000	      1856	r-x        	none          	libtracker.so_seg0ro
	43152	0x01e2f000	0x01e91000	       392	rw-        	none          	libtracker.so_seg1rw
	43153	0x01e91000	0x01e93000	         8	rw-        	none          	libtracker.so_seg2rw
	43174	0x020fb000	0x02105000	        40	r-x        	none          	libbsd.so_seg0ro
	43175	0x02105000	0x02106000	         4	rw-        	none          	libbsd.so_seg1rw
	43162	0x02142000	0x023d2000	      2624	r-x        	none          	libicui18n.so.57.2_seg0ro
	43163	0x023d2000	0x0243b000	       420	rw-        	none          	libicui18n.so.57.2_seg1rw
	43164	0x0243b000	0x0243c000	         4	rw-        	none          	libicui18n.so.57.2_seg2rw
	43149	0x026ab000	0x026c2000	        92	r-x        	none          	libtranslation.so_seg0ro
	43150	0x026c2000	0x026c7000	        20	rw-        	none          	libtranslation.so_seg1rw
	43160	0x026f4000	0x03f74000	     25088	r-x        	none          	libicudata.so.57.2_seg0ro
	43161	0x03f74000	0x03f75000	         4	rw-        	none          	libicudata.so.57.2_seg1rw
	43181	0x182de000	0x1843e000	      1408	rw-        	none          	heap
	43134	0x6046d000	0x60471000	        16	rw-k       	full          	user area
	43136	0x64aad000	0x64ab5000	        32	r-xSk      	full          	commpage
	43190	0x64ab5000	0x64ab6000	         4	rw-cS      	none          	server_memory
	43202	0x70ce2000	0x70d27000	       276	rw-s       	none          	w>TrackerWindow_5023_stack
	43135	0x7119a000	0x721a0000	     16408	rw-s       	none          	FtpPositive_5018_stack
	43192	0x721a0000	0x721d6000	       216	rw-cS      	none          	server_memory

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	2036364	    0	        796	some BLocker
	2040240	    0	       3552	Tracker node icon cache
	2042114	    0	       4368	Catalog
	2042296	    0	       3552	Catalog
	2042308	    0	        796	Catalog
	2042314	    0	       3552	some BBlockCache lock
	2042315	    0	        796	some BLocker
	2042317	    0	        796	some BLocker
	2042319	    0	        796	token space
	2042320	    0	       5018	BLooperList lock
	2042321	    0	        796	Light Lock
	2042322	    0	        796	some BLocker
	2042323	    0	       3552	PeriodicUpdatePoses
	2042324	    0	        796	Light Lock
	2042325	    0	       2418	AppServerLink_sLock
	2042326	    0	        796	LocaleRosterData
	2042327	    0	        796	Catalog
	2042329	    0	       3552	undo
	2042330	    0	        796	some BLocker
	2042331	    0	        796	some BLocker
	2042332	    0	        796	AppLooperPort
	2042333	    0	        796	BMessageQueue Lock
	2042334	    0	        796	BMessageQueue Lock
	2042346	    0	        796	virtual directory manager
	2042347	    0	        796	screen list
	2042348	    0	        796	clipboard
	2042349	    0	        796	width buffer
	2042351	    0	        796	BMessageQueue Lock
	2042352	    0	        796	FtpPositive
	2042359	    0	       5023	TrackerWindow
	2042365	    0	        796	Tracker shared icon cache
	2042373	    0	        738	some BLocker
	2042374	    0	        753	some BLocker

</details>

**Comment by humdingerb** [comment]
I tried with 32bit hrev57465, works there.
Then updated to hrev57709 and boom, got that crash.
Good thing, a recompile fixes it.

Now, I don't know: what hrev are the haikuports running? Are they uptodate enough to fix the app with a recompile? Would that break the app for people running beta4?

**Comment by unspacyar** [comment]
Sorry... I really forgot about this bug-report.  Thank you for your advice, @humdingerb .  I tried downloading and compiling from source using a nightly hrev (hrev58449 x86_gcc2), and now the application starts perfectly.   However, I also notice that the application from HaikuDepot is still crashing (tested on same hrev).

Thank you and hope you had a nice Christmas!

**Comment by humdingerb** [comment]
Belated Merry Xmas to you, too!
Thanks for the reminder, i forgot about it, too... :)
I updated the haikuports recipe, forcing a rebuild. HaikuDepot should have the working 32bit version shortly.
